name: Verify Compile

on:
  workflow_dispatch:

jobs:
  build:

    env:
      PROJECT: StereoKit.Templates.csproj
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: '2.7.5'
    - name: Build script
      run: ./Tools/Build-Nuget.ps1
